---
title: "particle_filter_MM"
author: "Sam"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.width=5, fig.height=4,fig.align = "center",cache=TRUE)
```


```{r, echo=FALSE, include=FALSE, warning=FALSE, message=FALSE}
library(ggplot2)
library(reshape)
library(grid)
library(dplyr)
library(gridExtra)
library(lme4)
library(reghelper)
library(RColorBrewer)
library(robustbase)
library(latex2exp)
library(tidyr)
library(readr)
library(stringr)
library(viridis)
library(patchwork)

paper_theme <- theme_light() + theme( axis.title.x = element_text(size=18),
  axis.text.x=element_text(colour="#292929", 
                           size = 14), 
  axis.title.y = element_text(size = 18, vjust = 1),
  axis.text.y  = element_text(size = 14, colour="#292929"),
  strip.text=element_text(size=16,color="black"),
strip.background = element_rect(colour = "grey50", fill = "white"),
panel.background = element_rect(fill = "white", colour = "grey50"),
  axis.ticks.x=element_blank(),axis.ticks.y=element_blank(),
  axis.line.x = element_line(colour = "black"), 
  axis.line.y = element_line(colour = "black"),
  legend.title=element_text(size=18),
  legend.text=element_text(size=15),
  panel.grid.major = element_blank(), panel.grid.minor = element_blank())


```


```{r}
df <- read.csv("mastermind_PF.csv")

df <- df %>%
        filter(round(log(num_particles, base=4)) == log(num_particles, base=4)) %>%
          group_by(r_id) %>%

      mutate(solved = 1*(true_code == guess)) %>%
      mutate(ever_solved = max(solved))

df_sub <- df %>% 
          group_by(r_id) %>%
          top_n(n=1, wt=guess_number) 


```


```{r}


ggplot(data=df_sub, aes(x=num_particles, y=ever_solved)) +
  stat_summary(fun="mean", geom="line") +
  
  stat_summary(fun.data="mean_se", geom="errorbar", width=0.01) +
  
  stat_summary(fun="mean", geom="point", size=2) +
  stat_summary(fun="mean", geom="point", size=1, color="white") +


  scale_x_continuous(trans = "log10", breaks = unique(df_sub$num_particles), labels = unique(df_sub$num_particles)) +
  paper_theme +
  xlab("Particles") + ylab("Ever solved")




# coord_cartesian(ylim=c(0.5,1))

```


```{r, fig.width=8, fig.height=3}

# First plot (Number of guesses)
p1 <- ggplot(data=df_sub, aes(x=num_particles, y=guess_number)) +
  geom_hline(linetype="dashed", yintercept=3.4) +
  stat_summary(fun="mean", geom="line") +
  stat_summary(fun.data="mean_se", geom="errorbar", width=0.01) +
  stat_summary(fun="mean", geom="point", size=2) +
  stat_summary(fun="mean", geom="point", size=1, color="white") +
  scale_x_continuous(trans = "log10", breaks = unique(df_sub$num_particles), labels = unique(df_sub$num_particles)) +
  paper_theme +
  xlab("Particles") + ylab("Number of guesses")

# Second plot (EIG quantile)
p2 <- ggplot(data=subset(df, (df$solved == 0) | (df$true_entropy_prev > 0)), aes(x=num_particles, y=EIG_quantile)) +
  geom_hline(yintercept=0.5) +
  stat_summary(fun.data="mean_se", geom="errorbar", width=0.01) +
  stat_summary(fun="mean", geom="point", size=2) +
  stat_summary(fun="mean", geom="point", size=1, color="white") +
  ylab("EIG quantile") + xlab("Particles") +
  scale_x_continuous(trans = "log10", breaks = unique(df_sub$num_particles), labels = unique(df_sub$num_particles)) +
  paper_theme

# Combine the two plots side by side using patchwork
combined_plot <- p1 + p2 + plot_layout(nrow = 1)

# Print the combined plot
combined_plot

```

```{r,  fig.width=9, fig.height=2}



ggplot(subset(df, (df$solved == 0) | (df$true_entropy_prev > 0)), aes(x = round(EIG_quantile, 1), group = num_particles)) +
  geom_bar(aes(y = ..prop..), stat = "count") +
  paper_theme +
  facet_wrap(~num_particles, nrow = 1) +
  ylab("Proportion") + xlab("EIG quantile") +
  scale_x_continuous(breaks=c(0,0.5, 1)) +
  theme(axis.text.x = element_text(angle = 0), strip.text = element_text(size = 12))


```