---
title: "analyze_minesweeper"
author: "Sam"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.width=5, fig.height=4,fig.align = "center",cache=TRUE)
```


```{r, echo=FALSE, include=FALSE, warning=FALSE, message=FALSE}
library(ggplot2)
library(reshape)
library(grid)
library(dplyr)
library(gridExtra)
library(lme4)
library(reghelper)
library(RColorBrewer)
library(robustbase)
library(latex2exp)
library(tidyr)
library(readr)
library(stringr)
library(viridis)
library(patchwork)

library(Cairo)

 # Install and load extrafont
 library(extrafont)
 library(showtext)

 # Add the DejaVu Serif font

 # Add the DejaVu Serif font
 font_add("DejaVu Serif", regular = "/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf")
 font_add("DejaVu Sans", regular = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf")



 loadfonts(device = "pdf") 


paper_theme <- theme_light() + theme(
  axis.text.x=element_text(colour="#292929",
                           size = 14), 
axis.title.x = element_text(size=18, family="DejaVu Sans"),
  axis.title.y = element_text(size = 18, vjust = 1,  family="DejaVu Sans"),
  axis.text.y  = element_text(size = 14, colour="#292929", family="DejaVu Sans"),
  strip.text=element_text(size=16,color="black", family="DejaVu Sans"),
strip.background = element_rect(colour = "grey50", fill = "white"),
panel.background = element_rect(fill = "white", colour = "grey50"),
  axis.ticks.x=element_blank(),axis.ticks.y=element_blank(),
  axis.line.x = element_line(colour = "black"), 
  axis.line.y = element_line(colour = "black"),
  legend.title=element_text(size=18, family="DejaVu Sans"),
  legend.text=element_text(size=15, family="DejaVu Sans"),
  panel.grid.major = element_blank(), panel.grid.minor = element_blank())


binomial_smooth <- function(...) {
  geom_smooth(method = "glm", method.args = list(family = "binomial"), ...)
}



```

```{r}

df <- read.csv("sudoku_simulation_results.csv")
epsilon <- 0

df <- df %>%
    filter(step < 20) %>%
       mutate(total_vars = n_unsolved + n_solved, RT = RT, step=step+1) %>%
        group_by(beta_rt, beta_error, complexity_threshold, stimulus_idx, simulation_idx) %>%
        mutate(timepoint = step/max(step)) %>%

        arrange(step) %>%
        mutate(progress = n_solved/total_vars)%>%
           mutate(n_errors = n_solved - n_correct) %>%
           mutate(p_marked = n_solved/total_vars) %>%
           mutate(p_correct = n_correct/total_vars) %>%
           mutate(p_error = n_errors / total_vars) %>%
          mutate(p_correct_given_marked = ifelse(n_solved > 0, n_correct/n_solved, NA)) %>%
         mutate(p_correct = p_correct + 0.5 * (timepoint * epsilon) * (1 - p_marked)) %>%
         mutate(p_error = p_error + 0.5 * (timepoint * epsilon) * (1 - p_marked)) %>%

         mutate(p_marked = p_marked + (1 - p_marked) * timepoint * epsilon) 

df_final <- df %>%
        group_by( beta_rt, beta_error, complexity_threshold, stimulus_idx, simulation_idx) %>%
          top_n(n=1, wt=step)

unique_complexities <- unique(df$complexity_threshold)
```


```{r, fig.width=5, fig.height=3.5}




ggplot(data=df, 
       aes(x=step, y=p_correct, color=complexity_threshold, group=complexity_threshold)) +
  stat_summary(fun="mean", geom="line", size=2) +
  scale_color_gradientn(colors=c("darkblue", "darkred", "orange"), 
                        breaks = unique_complexities, 
                        labels = function(x) paste(x, "bits"), transform="log2") +
  paper_theme + 
  theme(
  #  legend.direction = "horizontal",  # Make legend horizontal
    legend.justification = "center",
    legend.title.align = 0.5,
    legend.title = element_text(vjust=2, size=15),
    legend.text = element_text(size=13),
    legend.position = c(0.75, 0.3),
    legend.background = element_rect(fill = "transparent", color = NA),
    legend.key = element_rect(fill = "transparent", color = NA),
      strip.background = element_blank(),
    strip.text = element_text(vjust=-0.7),
    legend.key.width = unit(15, "pt"),     # Adjust key width
    legend.key.height = unit(16, "pt")     # Adjust key height
  ) +  
  labs(x = "Step", y = "Proportion solved", color = "Capacity")



ggplot(data=df, 
       aes(x=step, y=p_error, color=complexity_threshold, group=complexity_threshold)) +
  stat_summary(fun="mean", geom="line", size=2) +
  scale_color_gradientn(colors=c("darkblue", "darkred", "orange"), 
                        breaks = unique_complexities, 
                        labels = function(x) paste(x, "bits"), transform="log2") +
  paper_theme + 
  theme(
  #  legend.direction = "horizontal",  # Make legend horizontal
    legend.justification = "center",
    legend.title.align = 0.5,
    legend.title = element_text(vjust=2, size=15),
    legend.text = element_text(size=13),
    legend.position = c(0.75, 0.3),
    legend.background = element_rect(fill = "transparent", color = NA),
    legend.key = element_rect(fill = "transparent", color = NA),
      strip.background = element_blank(),
    strip.text = element_text(vjust=-0.7),
    legend.key.width = unit(15, "pt"),     # Adjust key width
    legend.key.height = unit(16, "pt")     # Adjust key height
  ) +  
  labs(x = "Step", y = "Proportion error", color = "Capacity")


ggplot(data=df, 
       aes(x=step, y=p_correct_given_marked, color=complexity_threshold, group=complexity_threshold)) +
  stat_summary(fun="mean", geom="line", size=2) +
  scale_color_gradientn(colors=c("darkblue", "darkred", "orange"), 
                        breaks = unique_complexities, 
                        labels = function(x) paste(x, "bits"), transform="log2") +
  paper_theme + 
  theme(
  #  legend.direction = "horizontal",  # Make legend horizontal
    legend.justification = "center",
    legend.title.align = 0.5,
    legend.title = element_text(vjust=2, size=15),
    legend.text = element_text(size=13),
#    legend.position = c(0.75, 0.3),
    legend.background = element_rect(fill = "transparent", color = NA),
    legend.key = element_rect(fill = "transparent", color = NA),
      strip.background = element_blank(),
    strip.text = element_text(vjust=-0.7),
    legend.key.width = unit(15, "pt"),     # Adjust key width
    legend.key.height = unit(16, "pt")     # Adjust key height
  ) +  
  labs(x = "Step", y = "P(correct | marked)", color = "Capacity")

```




```{r, fig.width=8.25, fig.height=3.5}

ggplot(data=df, 
       aes(x=step, y=p_marked, color=complexity_threshold, group=complexity_threshold)) +
  stat_summary(fun="mean", geom="line", size=2) +
  scale_color_gradientn(colors=c("darkblue", "darkred", "orange"), 
                        breaks = unique_complexities, 
                        labels = function(x) paste(x, "bits"), transform="log2") +
  paper_theme + 
  theme(
  #  legend.direction = "horizontal",  # Make legend horizontal
    legend.justification = "center",
    legend.title.align = 0.5,
    legend.title = element_text(vjust=1, size=16),
    legend.text = element_text(size=12),
   # legend.position = c(0.9, 0.26),
    legend.background = element_rect(fill = "transparent", color = NA),
    legend.key = element_rect(fill = "transparent", color = NA),
      strip.background = element_blank(),
    strip.text = element_text(vjust=-0.7),
    legend.key.width = unit(20, "pt"),     # Adjust key width
    legend.key.height = unit(16, "pt")     # Adjust key height
  ) +  
  scale_y_continuous(breaks=c(0,0.5,1)) +
  labs(x = "Step", y = "Proportion marked", color = "Capacity") +
  facet_wrap(~beta_error) +
    guides(color = guide_legend(override.aes = list(alpha = 0.8)))  # Adjust transparency\



ggplot(data=df, 
       aes(x=step, y=p_correct, color=complexity_threshold, group=complexity_threshold)) +
  stat_summary(fun="mean", geom="line", size=2) +
  scale_color_gradientn(colors=c("darkblue", "darkred", "orange"), 
                        breaks = unique_complexities, 
                        labels = function(x) paste(x, "bits"), transform="log2") +
  paper_theme + 
  theme(
  #  legend.direction = "horizontal",  # Make legend horizontal
    legend.justification = "center",
    legend.title.align = 0.5,
    legend.title = element_text(vjust=1, size=16),
    legend.text = element_text(size=12),
   # legend.position = c(0.9, 0.26),
    legend.background = element_rect(fill = "transparent", color = NA),
    legend.key = element_rect(fill = "transparent", color = NA),
      strip.background = element_blank(),
    strip.text = element_text(vjust=-0.7),
    legend.key.width = unit(20, "pt"),     # Adjust key width
    legend.key.height = unit(16, "pt")     # Adjust key height
  ) +  
  scale_y_continuous(breaks=c(0,0.5,1), limits=c(0,1)) +
  labs(x = "Step", y = "Proportion solved", color = "Capacity") +
  facet_wrap(~beta_error, 
             labeller = label_bquote(cols = .(ifelse(beta_error == 0, "No metacognition", "With metacognition")) ~ (beta[L] == .(beta_error))), nrow=1) +    guides(color = guide_legend(override.aes = list(alpha = 0.8)))  # Adjust transparency\



ggplot(data=df, 
       aes(x=step, y=p_correct_given_marked, color=complexity_threshold, group=complexity_threshold)) +
  stat_summary(fun="mean", geom="line", size=2) +
  scale_color_gradientn(colors=c("darkblue", "darkred", "orange"), 
                        breaks = unique_complexities, 
                        labels = function(x) paste(x, "bits"), transform="log2") +
  paper_theme + 
  theme(
  #  legend.direction = "horizontal",  # Make legend horizontal
    legend.justification = "center",
    legend.title.align = 0.5,
    legend.title = element_text(vjust=1, size=16),
    legend.text = element_text(size=12),
   # legend.position = c(0.9, 0.26),
    legend.background = element_rect(fill = "transparent", color = NA),
    legend.key = element_rect(fill = "transparent", color = NA),
      strip.background = element_blank(),
    strip.text = element_text(vjust=-0.7),
    legend.key.width = unit(20, "pt"),     # Adjust key width
    legend.key.height = unit(16, "pt")     # Adjust key height
  ) +  
  labs(x = "Step", y = "P(correct | marked)", color = "Capacity") +
  facet_wrap(~beta_error, 
             labeller = label_bquote(cols = .(ifelse(beta_error == 0, "No metacognition", "With metacognition")) ~ (beta[L] == .(beta_error))), nrow=1) +
    guides(color = guide_legend(override.aes = list(alpha = 0.8)))  # Adjust transparency\

ggplot(data=df, 
       aes(x=step, y=p_error, color=complexity_threshold, group=complexity_threshold)) +
  stat_summary(fun="mean", geom="line", size=2) +
  scale_color_gradientn(colors=c("darkblue", "darkred", "orange"), 
                        breaks = unique_complexities, 
                        labels = function(x) paste(x, "bits"), transform="log2") +
  paper_theme + 
  theme(
  #  legend.direction = "horizontal",  # Make legend horizontal
    legend.justification = "center",
    legend.title.align = 0.5,
    legend.title = element_text(vjust=1, size=16),
    legend.text = element_text(size=12),
    #legend.position = c(0.9, 0.26),
    legend.background = element_rect(fill = "transparent", color = NA),
    legend.key = element_rect(fill = "transparent", color = NA),
      strip.background = element_blank(),
    strip.text = element_text(vjust=-0.7),
    legend.key.width = unit(20, "pt"),     # Adjust key width
    legend.key.height = unit(16, "pt")     # Adjust key height
  ) +  
  labs(x = "Step", y = "Proportion error", color = "Capacity") +
  facet_wrap(~beta_error, 
             labeller = label_bquote(cols = .(ifelse(beta_error == 0, "No metacognition", "With metacognition")) ~ (beta[L] == .(beta_error))), nrow=1) +
  guides(color = guide_legend(override.aes = list(alpha = 0.8)))  # Adjust transparency\


```

```{r}


```

